# Generated by Django 4.0.3 on 2022-03-09 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0003_userprofile_address_userprofile_dob_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('duration', models.IntegerField()),
                ('pre_requisite', models.CharField(choices=[('higher_secondary', 'Higher Secondary'), ('graduate', 'Graduate'), ('under_graduate', 'Under Graduate'), ('post_graduate', 'Post Graduate')], max_length=20)),
                ('is_vocational', models.BooleanField(default=False)),
            ],
        ),
    ]
