# Generated by Django 4.0.3 on 2022-03-09 13:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0004_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('courses', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_profile.course')),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='user_profile.userprofile')),
                ('works_at', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_profile.department')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qualification', models.CharField(choices=[('higher_secondary', 'Higher Secondary'), ('graduate', 'Graduate'), ('under_graduate', 'Under Graduate'), ('post_graduate', 'Post Graduate')], max_length=20)),
                ('start_year', models.CharField(max_length=4)),
                ('courses', models.ManyToManyField(to='user_profile.course')),
                ('user_profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='user_profile.userprofile')),
            ],
        ),
    ]
