# Generated by Django 4.0.3 on 2022-03-10 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0008_subject_remove_teacher_works_at_course_subjects_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='teaches',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_profile.subject'),
        ),
    ]
