# Generated by Django 4.0.3 on 2022-03-10 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0009_alter_teacher_teaches'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='works_at',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='user_profile.department'),
        ),
    ]
