# Generated by Django 4.0.3 on 2022-03-10 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0012_remove_teacher_teaches_subject_taught_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='taught_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_profile.teacher'),
        ),
    ]
