# Generated by Django 4.0.3 on 2022-03-11 04:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0014_remove_teacher_works_at_delete_department'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subject',
            old_name='taught_by',
            new_name='teacher',
        ),
    ]
