# Generated by Django 4.0.3 on 2022-03-17 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0017_alter_student_start_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='courses',
            field=models.ManyToManyField(to='user_profile.course'),
        ),
    ]
