# Generated by Django 4.0.3 on 2022-03-21 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0018_alter_student_courses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='pre_requisite',
            field=models.CharField(choices=[('higher_secondary', 'Higher Secondary'), ('graduate', 'Graduate'), ('post_graduate', 'Post Graduate')], max_length=20),
        ),
        migrations.AlterField(
            model_name='student',
            name='courses',
            field=models.ManyToManyField(blank=True, null=True, to='user_profile.course'),
        ),
        migrations.AlterField(
            model_name='student',
            name='qualification',
            field=models.CharField(choices=[('higher_secondary', 'Higher Secondary'), ('graduate', 'Graduate'), ('post_graduate', 'Post Graduate')], max_length=20),
        ),
        migrations.AlterField(
            model_name='student',
            name='start_year',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
